import type { Question, SharoshiCategory } from "./types";

/**
 * 社会保険労務士 試験対策問題集
 * カテゴリ:
 *   labor-law      : 労働基準法
 *   safety         : 労働安全衛生法
 *   workers-comp   : 労災保険法
 *   employment-ins : 雇用保険法
 *   health-ins     : 健康保険法
 *   pension        : 年金法（国民年金・厚生年金）
 *   general-labor  : 労務管理その他の労働に関する一般常識
 *   general-social : 社会保険に関する一般常識
 */

export const sharoshiQuestions: Question[] = [
  // ==========================================================================
  // 労働基準法 (labor-law)
  // ==========================================================================
  {
    id: "sh-001",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者が労働者を解雇する場合、原則として少なくとも何日前に予告しなければならないか。",
    choices: ["14日前", "20日前", "30日前", "60日前"],
    answer: 2,
    explanation: "労働基準法第20条により、使用者は労働者を解雇しようとする場合、少なくとも30日前に予告しなければなりません。30日前に予告しない場合は、30日分以上の平均賃金（解雇予告手当）を支払う必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-002",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法で定められている法定労働時間は、1日何時間、1週何時間か。",
    choices: [
      "1日7時間、1週35時間",
      "1日8時間、1週40時間",
      "1日8時間、1週44時間",
      "1日9時間、1週45時間",
    ],
    answer: 1,
    explanation: "労働基準法第32条により、法定労働時間は1日8時間、1週40時間と定められています。ただし、特例措置対象事業場（常時10人未満の商業・映画等）では1週44時間が認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-003",
    type: "truefalse",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "使用者は、労働者に対して、毎週少なくとも1回の休日を与えなければならない。ただし、4週間を通じ4日以上の休日を与える場合はこの限りでない。",
    answer: true,
    explanation: "労働基準法第35条により、毎週少なくとも1回の休日（法定休日）を与えなければなりません。ただし、4週間を通じ4日以上の休日を与える「変形休日制」も認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-004",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、年次有給休暇の権利が発生するための要件として、雇入れの日から起算して何ヶ月間継続勤務し、全労働日の何割以上出勤した場合か。",
    choices: [
      "3ヶ月間・7割以上",
      "6ヶ月間・8割以上",
      "6ヶ月間・7割以上",
      "1年間・8割以上",
    ],
    answer: 1,
    explanation: "労働基準法第39条により、雇入れの日から6ヶ月間継続勤務し、全労働日の8割以上出勤した労働者に対して、年次有給休暇を与えなければなりません。初年度は10日が付与されます。",
    source: "hardcoded",
  },
  {
    id: "sh-005",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、時間外労働に対する割増賃金率は、通常の場合、何%以上か。",
    choices: ["10%以上", "15%以上", "25%以上", "50%以上"],
    answer: 2,
    explanation: "労働基準法第37条により、時間外労働に対する割増賃金率は25%以上です。なお、深夜労働（午後10時から午前5時）も25%以上、休日労働は35%以上の割増賃金が必要です。月60時間を超える時間外労働は50%以上となります。",
    source: "hardcoded",
  },
  {
    id: "sh-006",
    type: "truefalse",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、賃金は、通貨で、直接労働者に、その全額を、毎月1回以上、一定の期日を定めて支払わなければならない。",
    answer: true,
    explanation: "労働基準法第24条に定める「賃金支払の5原則」です。(1)通貨払い、(2)直接払い、(3)全額払い、(4)毎月1回以上払い、(5)一定期日払いの5原則が定められています。",
    source: "hardcoded",
  },
  {
    id: "sh-007",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、原則として使用してはならない年齢は次のうちどれか。",
    choices: [
      "満13歳に満たない児童",
      "満15歳に達した日以後の最初の3月31日が終了するまでの児童",
      "満16歳未満の年少者",
      "満18歳未満の年少者",
    ],
    answer: 1,
    explanation: "労働基準法第56条により、使用者は、児童が満15歳に達した日以後の最初の3月31日が終了するまで、これを使用してはなりません（義務教育終了まで）。ただし、一部軽易な業務については例外があります。",
    source: "hardcoded",
  },
  {
    id: "sh-008",
    type: "truefalse",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、産前の休業は、6週間（多胎妊娠の場合は14週間）以内の女性が請求した場合に与えなければならず、産後は8週間を経過しない女性を就業させてはならない。",
    answer: true,
    explanation: "労働基準法第65条により、産前6週間（多胎妊娠は14週間）は請求があった場合に休業させ、産後8週間は原則就業させてはなりません。ただし、産後6週間を経過した女性が請求した場合、医師が支障ないと認めた業務には就かせることができます。",
    source: "hardcoded",
  },
  {
    id: "sh-009",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、就業規則の作成義務があるのは、常時何人以上の労働者を使用する事業場か。",
    choices: ["5人以上", "10人以上", "30人以上", "50人以上"],
    answer: 1,
    explanation: "労働基準法第89条により、常時10人以上の労働者を使用する事業場では、就業規則を作成し、行政官庁（所轄労働基準監督署長）に届け出なければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-010",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法における36協定（サブロク協定）とは、何条に基づく労使協定か。",
    choices: ["第32条", "第34条", "第36条", "第39条"],
    answer: 2,
    explanation: "36協定は労働基準法第36条に基づく労使協定です。使用者が法定労働時間を超えて労働させる場合や、法定休日に労働させる場合には、労働者の過半数代表者と書面による協定を結び、行政官庁に届け出る必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-011",
    type: "truefalse",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、労働契約の期間は、期間の定めのないものを除き、原則として3年を超えてはならない。",
    answer: true,
    explanation: "労働基準法第14条により、労働契約の期間は原則3年を超えてはなりません。ただし、専門的知識等を有する労働者との契約や満60歳以上の労働者との契約は5年まで認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-012",
    type: "choice",
    grade: 1,
    category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、休憩時間について正しいものはどれか。",
    choices: [
      "労働時間が6時間を超える場合は30分以上、8時間を超える場合は45分以上",
      "労働時間が6時間を超える場合は45分以上、8時間を超える場合は1時間以上",
      "労働時間が4時間を超える場合は30分以上、6時間を超える場合は45分以上",
      "労働時間が8時間を超える場合のみ1時間以上",
    ],
    answer: 1,
    explanation: "労働基準法第34条により、労働時間が6時間を超える場合は少なくとも45分、8時間を超える場合は少なくとも1時間の休憩を、労働時間の途中に与えなければなりません。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労働安全衛生法 (safety)
  // ==========================================================================
  {
    id: "sh-013",
    type: "choice",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、総括安全衛生管理者を選任しなければならない事業場の規模は、建設業の場合、常時何人以上の労働者を使用する事業場か。",
    choices: ["50人以上", "100人以上", "300人以上", "1000人以上"],
    answer: 1,
    explanation: "労働安全衛生法第10条及び施行令により、総括安全衛生管理者の選任義務は業種により異なります。建設業・運送業等は100人以上、製造業等は300人以上、その他は1000人以上です。",
    source: "hardcoded",
  },
  {
    id: "sh-014",
    type: "truefalse",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "事業者は、常時50人以上の労働者を使用する事業場においては、衛生管理者を選任しなければならない。",
    answer: true,
    explanation: "労働安全衛生法第12条により、常時50人以上の労働者を使用する事業場では、衛生管理者を選任しなければなりません。選任すべき人数は事業場の規模により異なります。",
    source: "hardcoded",
  },
  {
    id: "sh-015",
    type: "choice",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、産業医を選任しなければならない事業場の規模は、常時何人以上の労働者を使用する事業場か。",
    choices: ["10人以上", "30人以上", "50人以上", "100人以上"],
    answer: 2,
    explanation: "労働安全衛生法第13条により、常時50人以上の労働者を使用する事業場では、産業医を選任しなければなりません。常時1000人以上の事業場等では専属の産業医が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-016",
    type: "choice",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、事業者が労働者に対して実施しなければならない一般健康診断の頻度は、原則として何回か。",
    choices: [
      "6ヶ月に1回",
      "1年以内ごとに1回",
      "2年以内ごとに1回",
      "3年以内ごとに1回",
    ],
    answer: 1,
    explanation: "労働安全衛生法第66条及び規則第44条により、事業者は常時使用する労働者に対し、1年以内ごとに1回、定期に一般健康診断を行わなければなりません。特定業務従事者は6ヶ月以内ごとに1回です。",
    source: "hardcoded",
  },
  {
    id: "sh-017",
    type: "truefalse",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、事業者は、常時50人以上の労働者を使用する事業場においては、安全委員会と衛生委員会（又は安全衛生委員会）を設置しなければならない。",
    answer: false,
    explanation: "衛生委員会は常時50人以上の全業種で設置義務がありますが、安全委員会は一定の業種（建設業、製造業等）の常時50人以上の事業場に限られます。すべての業種で安全委員会の設置義務があるわけではありません。",
    source: "hardcoded",
  },
  {
    id: "sh-018",
    type: "choice",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、ストレスチェック制度の実施義務がある事業場の規模は、常時何人以上の労働者を使用する事業場か。",
    choices: ["10人以上", "30人以上", "50人以上", "100人以上"],
    answer: 2,
    explanation: "労働安全衛生法第66条の10により、常時50人以上の労働者を使用する事業場では、1年以内ごとに1回、ストレスチェックを実施しなければなりません。50人未満は当面の間努力義務です。",
    source: "hardcoded",
  },
  {
    id: "sh-019",
    type: "truefalse",
    grade: 1,
    category: "safety" as SharoshiCategory,
    question: "事業者は、労働者を雇い入れたときは、当該労働者に対し、その従事する業務に関する安全又は衛生のための教育を行わなければならない。",
    answer: true,
    explanation: "労働安全衛生法第59条第1項により、事業者は労働者を雇い入れたときは、安全衛生教育を行わなければなりません。また、作業内容を変更したときも同様です。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労災保険法 (workers-comp)
  // ==========================================================================
  {
    id: "sh-020",
    type: "choice",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "労災保険の休業補償給付の支給額は、休業1日につき給付基礎日額の何%相当額か。",
    choices: ["40%", "50%", "60%", "80%"],
    answer: 2,
    explanation: "労災保険法により、休業補償給付は休業4日目から給付基礎日額の60%が支給されます。これに加え、休業特別支給金として20%が上乗せされるため、実質的には80%の補償を受けることができます。",
    source: "hardcoded",
  },
  {
    id: "sh-021",
    type: "choice",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "労災保険の休業補償給付は、休業開始から何日目から支給されるか。",
    choices: ["初日から", "2日目から", "4日目から", "8日目から"],
    answer: 2,
    explanation: "労災保険の休業補償給付は、休業4日目から支給されます。最初の3日間（待期期間）は事業主が労働基準法に基づく休業補償（平均賃金の60%）を行います。",
    source: "hardcoded",
  },
  {
    id: "sh-022",
    type: "truefalse",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "通勤災害は、労災保険の保護の対象である。",
    answer: true,
    explanation: "労災保険法第7条により、通勤災害も労災保険の保護対象です。通勤とは、住居と就業の場所との間の往復等を合理的な経路・方法により行うことをいいます。",
    source: "hardcoded",
  },
  {
    id: "sh-023",
    type: "choice",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "労災保険法上、遺族補償年金の受給資格者のうち、最先順位者が受給権者となるが、最先順位者はどれか。",
    choices: [
      "労働者の子",
      "労働者の配偶者（事実婚含む）",
      "労働者の父母",
      "労働者の孫",
    ],
    answer: 1,
    explanation: "遺族補償年金の受給資格者の順位は、(1)配偶者、(2)子、(3)父母、(4)孫、(5)祖父母、(6)兄弟姉妹です。ただし、妻以外の遺族は一定の年齢要件等があります。",
    source: "hardcoded",
  },
  {
    id: "sh-024",
    type: "choice",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "労災保険の障害補償年金は、障害等級第何級以上の場合に支給されるか。",
    choices: ["第3級以上", "第5級以上", "第7級以上", "第10級以上"],
    answer: 2,
    explanation: "障害補償年金は障害等級第1級から第7級までの障害が残った場合に支給されます。第8級から第14級までの障害には障害補償一時金が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-025",
    type: "truefalse",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "労災保険は、原則として労働者を使用するすべての事業に適用され、保険料は全額事業主が負担する。",
    answer: true,
    explanation: "労災保険は原則としてすべての事業に強制適用され、保険料は全額事業主負担です。労働者の負担はありません。これは健康保険や厚生年金（労使折半）とは異なる特徴です。",
    source: "hardcoded",
  },
  {
    id: "sh-026",
    type: "choice",
    grade: 1,
    category: "workers-comp" as SharoshiCategory,
    question: "業務上の傷病が療養開始後1年6ヶ月を経過しても治らない場合、一定の傷病等級に該当すれば支給される給付はどれか。",
    choices: [
      "障害補償年金",
      "傷病補償年金",
      "休業補償給付",
      "療養補償給付",
    ],
    answer: 1,
    explanation: "傷病補償年金は、業務上の傷病が療養開始後1年6ヶ月を経過した日（または同日後）において、傷病が治っておらず、傷病等級（第1級〜第3級）に該当する場合に支給されます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 雇用保険法 (employment-ins)
  // ==========================================================================
  {
    id: "sh-027",
    type: "choice",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の基本手当の受給資格を得るには、原則として離職の日以前何年間に被保険者期間が通算して何ヶ月以上必要か。",
    choices: [
      "1年間に6ヶ月以上",
      "2年間に12ヶ月以上",
      "2年間に6ヶ月以上",
      "1年間に12ヶ月以上",
    ],
    answer: 1,
    explanation: "雇用保険法により、基本手当の受給資格は、原則として離職の日以前2年間に被保険者期間が通算して12ヶ月以上ある場合に認められます。特定受給資格者等の場合は、離職前1年間に6ヶ月以上で足ります。",
    source: "hardcoded",
  },
  {
    id: "sh-028",
    type: "choice",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の基本手当の待期期間は何日間か。",
    choices: ["3日間", "7日間", "14日間", "30日間"],
    answer: 1,
    explanation: "雇用保険法第21条により、基本手当は求職の申込みをした日以後、失業の状態にある日が通算7日間（待期期間）経過するまでは支給されません。自己都合退職の場合はさらに給付制限期間があります。",
    source: "hardcoded",
  },
  {
    id: "sh-029",
    type: "choice",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の基本手当の日額は、原則として賃金日額の何%〜何%か。",
    choices: [
      "40%〜60%",
      "45%〜80%",
      "50%〜80%",
      "60%〜90%",
    ],
    answer: 2,
    explanation: "基本手当の日額は、原則として賃金日額の50%〜80%です。賃金が低い人ほど高い率が適用されます。60歳以上65歳未満は45%〜80%です。",
    source: "hardcoded",
  },
  {
    id: "sh-030",
    type: "truefalse",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の被保険者には、一般被保険者、高年齢被保険者、短期雇用特例被保険者、日雇労働被保険者の4種類がある。",
    answer: true,
    explanation: "雇用保険の被保険者は4種類に区分されます。65歳以上の労働者は高年齢被保険者、季節的に雇用される者等は短期雇用特例被保険者、日雇労働者は日雇労働被保険者、それ以外は一般被保険者です。",
    source: "hardcoded",
  },
  {
    id: "sh-031",
    type: "choice",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の育児休業給付金は、原則として休業開始時賃金日額の何%相当額が支給されるか（休業開始から180日目まで）。",
    choices: ["50%", "60%", "67%", "80%"],
    answer: 2,
    explanation: "育児休業給付金は、休業開始から180日目までは賃金日額の67%、181日目以降は50%が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-032",
    type: "choice",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険法上、自己都合退職の場合の給付制限期間は、原則として待期期間満了後何ヶ月か。",
    choices: ["1ヶ月", "2ヶ月", "3ヶ月", "6ヶ月"],
    answer: 1,
    explanation: "2020年10月の改正により、正当な理由のない自己都合退職の場合、5年間のうち2回までは給付制限期間が2ヶ月に短縮されました。3回目以降は従来どおり3ヶ月です。",
    source: "hardcoded",
  },
  {
    id: "sh-033",
    type: "truefalse",
    grade: 1,
    category: "employment-ins" as SharoshiCategory,
    question: "雇用保険法上、教育訓練給付金は、一定の教育訓練を受けた場合に、その費用の一部が支給される制度である。",
    answer: true,
    explanation: "教育訓練給付制度は、厚生労働大臣が指定する教育訓練を受講し修了した場合に、その費用の一部（一般教育訓練は20%、最大10万円）が支給されます。専門実践教育訓練は最大70%です。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 健康保険法 (health-ins)
  // ==========================================================================
  {
    id: "sh-034",
    type: "choice",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の被保険者が業務外の事由により療養を受ける場合、一部負担金の割合は、原則として何割か（70歳未満）。",
    choices: ["1割", "2割", "3割", "5割"],
    answer: 2,
    explanation: "健康保険法により、70歳未満の被保険者の一部負担金は3割です。70歳以上75歳未満は原則2割（現役並み所得者は3割）、小学校就学前の子は2割です。",
    source: "hardcoded",
  },
  {
    id: "sh-035",
    type: "choice",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の傷病手当金は、連続する3日間の待期期間の後、何日目から支給されるか。",
    choices: ["2日目", "4日目", "8日目", "15日目"],
    answer: 1,
    explanation: "傷病手当金は、労務に服することができなくなった日から起算して3日間の待期期間を経た後、4日目から支給されます。待期期間は連続する3日間が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-036",
    type: "choice",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の傷病手当金の支給期間は、支給開始日から通算して最長何年間か。",
    choices: ["6ヶ月", "1年", "1年6ヶ月", "3年"],
    answer: 2,
    explanation: "2022年1月の改正により、傷病手当金の支給期間は、支給開始日から通算して1年6ヶ月です（以前は支給開始日から起算して1年6ヶ月）。出勤した期間は通算されません。",
    source: "hardcoded",
  },
  {
    id: "sh-037",
    type: "truefalse",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の被扶養者になるためには、主として被保険者の収入により生計を維持していることが必要であり、年間収入が130万円未満であることが要件の一つとされている。",
    answer: true,
    explanation: "被扶養者の収入要件は、年間収入130万円未満（60歳以上又は障害者は180万円未満）かつ被保険者の年間収入の2分の1未満であることです。",
    source: "hardcoded",
  },
  {
    id: "sh-038",
    type: "choice",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の出産手当金は、出産日以前何日間・出産日後何日間の期間、支給されるか。",
    choices: [
      "産前42日・産後42日",
      "産前42日・産後56日",
      "産前56日・産後56日",
      "産前56日・産後42日",
    ],
    answer: 1,
    explanation: "出産手当金は、出産日（出産が予定日後の場合は出産予定日）以前42日（多胎妊娠は98日）から出産日後56日までの期間について支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-039",
    type: "choice",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の出産育児一時金の金額は、1児につきいくらか（産科医療補償制度加入の場合）。",
    choices: ["30万円", "42万円", "50万円", "55万円"],
    answer: 2,
    explanation: "2023年4月の改正により、出産育児一時金は1児につき50万円に引き上げられました（以前は42万円）。",
    source: "hardcoded",
  },
  {
    id: "sh-040",
    type: "truefalse",
    grade: 1,
    category: "health-ins" as SharoshiCategory,
    question: "健康保険の保険料は、事業主と被保険者が折半して負担する。",
    answer: true,
    explanation: "健康保険法第161条により、健康保険の保険料は原則として事業主と被保険者が折半で負担します。ただし、健康保険組合は規約で事業主の負担割合を増加させることができます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 年金法 (pension)
  // ==========================================================================
  {
    id: "sh-041",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "国民年金の第1号被保険者とは、次のうちどれか。",
    choices: [
      "会社員や公務員",
      "20歳以上60歳未満の自営業者・学生等",
      "第2号被保険者の被扶養配偶者",
      "65歳以上の年金受給者",
    ],
    answer: 1,
    explanation: "国民年金の第1号被保険者は、日本国内に住所を有する20歳以上60歳未満の者で、第2号被保険者・第3号被保険者以外の者（自営業者、学生、無職等）です。",
    source: "hardcoded",
  },
  {
    id: "sh-042",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の受給資格期間は、原則として何年以上か。",
    choices: ["10年以上", "15年以上", "20年以上", "25年以上"],
    answer: 0,
    explanation: "2017年8月の改正により、老齢基礎年金の受給資格期間は25年から10年に短縮されました。保険料納付済期間と保険料免除期間等を合算した期間が10年以上あれば受給できます。",
    source: "hardcoded",
  },
  {
    id: "sh-043",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の支給開始年齢は、原則として何歳からか。",
    choices: ["60歳", "62歳", "65歳", "70歳"],
    answer: 2,
    explanation: "老齢基礎年金は原則として65歳から支給されます。繰上げ受給（60歳〜64歳）も可能ですが年金額が減額され、繰下げ受給（66歳〜75歳）では増額されます。",
    source: "hardcoded",
  },
  {
    id: "sh-044",
    type: "truefalse",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の繰下げ受給をした場合、1ヶ月当たり0.7%の割合で年金額が増額される。",
    answer: true,
    explanation: "老齢基礎年金の繰下げ受給は、66歳から75歳まで可能で、1ヶ月当たり0.7%増額されます。最大で75歳まで繰り下げた場合、84%（0.7%×120ヶ月）増額となります。",
    source: "hardcoded",
  },
  {
    id: "sh-045",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "厚生年金保険の保険料率は、標準報酬月額および標準賞与額の何%か。",
    choices: ["8.914%", "16.058%", "18.3%", "20.0%"],
    answer: 2,
    explanation: "厚生年金保険の保険料率は18.3%（2017年9月以降固定）で、事業主と被保険者が折半（各9.15%）で負担します。",
    source: "hardcoded",
  },
  {
    id: "sh-046",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "遺族基礎年金を受給できる遺族は、次のうちどれか。",
    choices: [
      "被保険者の配偶者のみ",
      "被保険者の子のある配偶者又は子",
      "被保険者の父母又は祖父母",
      "被保険者のすべての遺族",
    ],
    answer: 1,
    explanation: "遺族基礎年金は、死亡した被保険者等に生計を維持されていた「子のある配偶者」又は「子」に支給されます。子とは、18歳到達年度末までの子又は20歳未満で障害等級1級・2級の子です。",
    source: "hardcoded",
  },
  {
    id: "sh-047",
    type: "truefalse",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "障害基礎年金は、障害等級1級又は2級に該当する場合に支給される。3級の場合は障害基礎年金は支給されない。",
    answer: true,
    explanation: "障害基礎年金は障害等級1級又は2級の場合に支給されます。3級は障害基礎年金の対象外ですが、厚生年金の被保険者であれば障害厚生年金（3級）が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-048",
    type: "choice",
    grade: 1,
    category: "pension" as SharoshiCategory,
    question: "国民年金の第1号被保険者の保険料は、令和5年度においていくらか（月額）。",
    choices: ["14,460円", "16,520円", "16,980円", "18,300円"],
    answer: 1,
    explanation: "国民年金の保険料は毎年度改定されます。令和5年度は月額16,520円です。なお、付加保険料として月額400円を追加で納めることもできます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労務管理その他の労働に関する一般常識 (general-labor)
  // ==========================================================================
  {
    id: "sh-049",
    type: "choice",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "労働契約法上、使用者は、労働者と合意することなく、就業規則を変更することにより、労働者の不利益に労働契約の内容を変更することは原則としてどうか。",
    choices: [
      "自由にできる",
      "労働基準監督署の許可があればできる",
      "できない",
      "合理的な理由があればできる",
    ],
    answer: 2,
    explanation: "労働契約法第9条により、使用者は、労働者と合意することなく、就業規則の変更により労働条件を不利益に変更することはできません。ただし、第10条で合理的な変更であり周知されている場合の例外が規定されています。",
    source: "hardcoded",
  },
  {
    id: "sh-050",
    type: "choice",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "最低賃金法上、最低賃金の種類として正しいものはどれか。",
    choices: [
      "全国最低賃金と都道府県最低賃金",
      "地域別最低賃金と特定最低賃金",
      "基本最低賃金と特別最低賃金",
      "法定最低賃金と協定最低賃金",
    ],
    answer: 1,
    explanation: "最低賃金には「地域別最低賃金」と「特定最低賃金（産業別最低賃金）」の2種類があります。地域別最低賃金は都道府県ごとに設定され、すべての労働者に適用されます。",
    source: "hardcoded",
  },
  {
    id: "sh-051",
    type: "truefalse",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "男女雇用機会均等法は、募集・採用、配置・昇進等における性別を理由とする差別を禁止している。",
    answer: true,
    explanation: "男女雇用機会均等法第5条・第6条により、事業主は労働者の募集・採用、配置・昇進・降格・教育訓練、福利厚生、退職・解雇等について、性別を理由とする差別的取扱いをしてはなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-052",
    type: "choice",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "育児・介護休業法上、育児休業は、原則として子が何歳に達するまでの間取得できるか。",
    choices: [
      "6ヶ月に達するまで",
      "1歳に達するまで",
      "1歳6ヶ月に達するまで",
      "3歳に達するまで",
    ],
    answer: 1,
    explanation: "育児休業は原則として子が1歳に達するまで取得できます。保育所に入れない等の場合は1歳6ヶ月まで、さらに再延長で2歳まで延長可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-053",
    type: "choice",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "労働者派遣法上、派遣先の同一の組織単位における同一の派遣労働者の受入期間の上限は何年か。",
    choices: ["1年", "2年", "3年", "5年"],
    answer: 2,
    explanation: "労働者派遣法により、同一の組織単位（いわゆる課やグループ）における同一の派遣労働者の受入れは3年が上限です。事業所単位でも原則3年ですが、過半数労働組合等への意見聴取により延長可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-054",
    type: "truefalse",
    grade: 1,
    category: "general-labor" as SharoshiCategory,
    question: "パートタイム・有期雇用労働法は、正規雇用労働者と非正規雇用労働者の間の不合理な待遇差を禁止する、いわゆる「同一労働同一賃金」の原則を定めている。",
    answer: true,
    explanation: "パートタイム・有期雇用労働法第8条・第9条により、正規雇用労働者と短時間・有期雇用労働者の間の不合理な待遇差が禁止されています。職務内容、配置変更の範囲等を考慮して判断されます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 社会保険に関する一般常識 (general-social)
  // ==========================================================================
  {
    id: "sh-055",
    type: "choice",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "国民健康保険の保険者はどれか。",
    choices: [
      "国",
      "都道府県及び市町村（特別区を含む）と国民健康保険組合",
      "全国健康保険協会のみ",
      "社会保険庁",
    ],
    answer: 1,
    explanation: "国民健康保険の保険者は、都道府県及び市町村（特別区を含む）と国民健康保険組合です。2018年度から都道府県も保険者に加わり、財政運営の責任主体となっています。",
    source: "hardcoded",
  },
  {
    id: "sh-056",
    type: "choice",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "後期高齢者医療制度の対象者は、原則として何歳以上か。",
    choices: ["60歳以上", "65歳以上", "70歳以上", "75歳以上"],
    answer: 3,
    explanation: "後期高齢者医療制度は、75歳以上の者（および65歳以上75歳未満で一定の障害の状態にあると認定された者）を対象としています。窓口負担は原則1割（現役並み所得者は3割、一定以上所得者は2割）です。",
    source: "hardcoded",
  },
  {
    id: "sh-057",
    type: "truefalse",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "介護保険の第1号被保険者とは、65歳以上の者であり、第2号被保険者とは、40歳以上65歳未満の医療保険加入者である。",
    answer: true,
    explanation: "介護保険法により、第1号被保険者は65歳以上の者、第2号被保険者は40歳以上65歳未満の医療保険加入者です。第2号被保険者は特定疾病が原因の場合にのみ介護サービスを受けられます。",
    source: "hardcoded",
  },
  {
    id: "sh-058",
    type: "choice",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "児童手当の支給対象年齢は、原則として何歳に達する日以後の最初の3月31日までか。",
    choices: [
      "12歳（小学校修了まで）",
      "15歳（中学校修了まで）",
      "18歳（高校修了まで）",
      "20歳まで",
    ],
    answer: 1,
    explanation: "児童手当は、中学校修了まで（15歳に達する日以後の最初の3月31日まで）の児童を養育している者に支給されます。なお、2024年10月からは高校生年代まで拡充されています。",
    source: "hardcoded",
  },
  {
    id: "sh-059",
    type: "choice",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "確定拠出年金（DC）について正しいものはどれか。",
    choices: [
      "運用リスクは事業主が負う",
      "運用リスクは加入者自身が負う",
      "給付額があらかじめ確定している",
      "国が運用を行う",
    ],
    answer: 1,
    explanation: "確定拠出年金（DC）は、拠出された掛金を加入者自身が運用し、その運用結果に基づいて給付額が決まる制度です。運用リスクは加入者が負います。これに対し、確定給付年金（DB）は給付額があらかじめ確定しています。",
    source: "hardcoded",
  },
  {
    id: "sh-060",
    type: "truefalse",
    grade: 1,
    category: "general-social" as SharoshiCategory,
    question: "社会保険労務士は、社会保険労務士法に基づき、労働社会保険に関する法令に基づく申請書等の作成・提出代行、労務管理等の相談指導等を業とする国家資格者である。",
    answer: true,
    explanation: "社会保険労務士法第2条に規定される社労士の業務には、(1)申請書等の作成、(2)提出代行、(3)事務代理、(4)紛争解決手続代理、(5)相談・指導等があります。労務管理の専門家としての国家資格です。",
    source: "hardcoded",
  },
];

// ---------------------------------------------------------------------------
// ヘルパー関数
// ---------------------------------------------------------------------------

export function getSharoshiQuestions(category?: SharoshiCategory): Question[] {
  if (!category) return sharoshiQuestions;
  return sharoshiQuestions.filter((q) => q.category === category);
}

export function getRandomSharoshiQuestions(count: number): Question[] {
  const shuffled = [...sharoshiQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
