import type { Question, SharoshiCategory } from "./types";

/**
 * 社会保険労務士 試験対策問題集 (約240問)
 * カテゴリ:
 *   labor-law      : 労働基準法
 *   safety         : 労働安全衛生法
 *   workers-comp   : 労災保険法
 *   employment-ins : 雇用保険法
 *   health-ins     : 健康保険法
 *   pension        : 年金法（国民年金・厚生年金）
 *   general-labor  : 労務管理その他の労働に関する一般常識
 *   general-social : 社会保険に関する一般常識
 */

export const sharoshiQuestions: Question[] = [
  // ==========================================================================
  // 労働基準法 (labor-law) — 30問
  // ==========================================================================
  {
    id: "sh-001", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者が労働者を解雇する場合、原則として少なくとも何日前に予告しなければならないか。",
    choices: ["14日前", "20日前", "30日前", "60日前"],
    answer: 2,
    explanation: "労働基準法第20条により、使用者は労働者を解雇しようとする場合、少なくとも30日前に予告しなければなりません。30日前に予告しない場合は、30日分以上の平均賃金（解雇予告手当）を支払う必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-002", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法で定められている法定労働時間は、1日何時間、1週何時間か。",
    choices: ["1日7時間、1週35時間", "1日8時間、1週40時間", "1日8時間、1週44時間", "1日9時間、1週45時間"],
    answer: 1,
    explanation: "労働基準法第32条により、法定労働時間は1日8時間、1週40時間と定められています。ただし、特例措置対象事業場（常時10人未満の商業・映画等）では1週44時間が認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-003", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "使用者は、労働者に対して、毎週少なくとも1回の休日を与えなければならない。ただし、4週間を通じ4日以上の休日を与える場合はこの限りでない。",
    answer: true,
    explanation: "労働基準法第35条により、毎週少なくとも1回の休日（法定休日）を与えなければなりません。ただし、4週間を通じ4日以上の休日を与える「変形休日制」も認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-004", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、年次有給休暇の権利が発生するための要件として、雇入れの日から起算して何ヶ月間継続勤務し、全労働日の何割以上出勤した場合か。",
    choices: ["3ヶ月間・7割以上", "6ヶ月間・8割以上", "6ヶ月間・7割以上", "1年間・8割以上"],
    answer: 1,
    explanation: "労働基準法第39条により、雇入れの日から6ヶ月間継続勤務し、全労働日の8割以上出勤した労働者に対して、年次有給休暇を与えなければなりません。初年度は10日が付与されます。",
    source: "hardcoded",
  },
  {
    id: "sh-005", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、時間外労働に対する割増賃金率は、通常の場合、何%以上か。",
    choices: ["10%以上", "15%以上", "25%以上", "50%以上"],
    answer: 2,
    explanation: "労働基準法第37条により、時間外労働に対する割増賃金率は25%以上です。深夜労働（午後10時から午前5時）も25%以上、休日労働は35%以上です。月60時間を超える時間外労働は50%以上となります。",
    source: "hardcoded",
  },
  {
    id: "sh-006", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、賃金は、通貨で、直接労働者に、その全額を、毎月1回以上、一定の期日を定めて支払わなければならない。",
    answer: true,
    explanation: "労働基準法第24条に定める「賃金支払の5原則」です。(1)通貨払い、(2)直接払い、(3)全額払い、(4)毎月1回以上払い、(5)一定期日払いの5原則が定められています。",
    source: "hardcoded",
  },
  {
    id: "sh-007", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、原則として使用してはならない年齢は次のうちどれか。",
    choices: ["満13歳に満たない児童", "満15歳に達した日以後の最初の3月31日が終了するまでの児童", "満16歳未満の年少者", "満18歳未満の年少者"],
    answer: 1,
    explanation: "労働基準法第56条により、使用者は、児童が満15歳に達した日以後の最初の3月31日が終了するまで、これを使用してはなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-008", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、産前の休業は、6週間（多胎妊娠の場合は14週間）以内の女性が請求した場合に与えなければならず、産後は8週間を経過しない女性を就業させてはならない。",
    answer: true,
    explanation: "労働基準法第65条により、産前6週間（多胎妊娠は14週間）は請求があった場合に休業させ、産後8週間は原則就業させてはなりません。ただし、産後6週間を経過した女性が請求した場合、医師が支障ないと認めた業務には就かせることができます。",
    source: "hardcoded",
  },
  {
    id: "sh-009", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、就業規則の作成義務があるのは、常時何人以上の労働者を使用する事業場か。",
    choices: ["5人以上", "10人以上", "30人以上", "50人以上"],
    answer: 1,
    explanation: "労働基準法第89条により、常時10人以上の労働者を使用する事業場では、就業規則を作成し、行政官庁（所轄労働基準監督署長）に届け出なければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-010", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法における36協定（サブロク協定）とは、何条に基づく労使協定か。",
    choices: ["第32条", "第34条", "第36条", "第39条"],
    answer: 2,
    explanation: "36協定は労働基準法第36条に基づく労使協定です。法定労働時間を超えて労働させる場合や、法定休日に労働させる場合には、書面による協定を結び、行政官庁に届け出る必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-011", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、労働契約の期間は、期間の定めのないものを除き、原則として3年を超えてはならない。",
    answer: true,
    explanation: "労働基準法第14条により、労働契約の期間は原則3年を超えてはなりません。ただし、専門的知識等を有する労働者や満60歳以上の労働者との契約は5年まで認められています。",
    source: "hardcoded",
  },
  {
    id: "sh-012", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、休憩時間について正しいものはどれか。",
    choices: ["労働時間が6時間を超える場合は30分以上、8時間を超える場合は45分以上", "労働時間が6時間を超える場合は45分以上、8時間を超える場合は1時間以上", "労働時間が4時間を超える場合は30分以上、6時間を超える場合は45分以上", "労働時間が8時間を超える場合のみ1時間以上"],
    answer: 1,
    explanation: "労働基準法第34条により、労働時間が6時間を超える場合は少なくとも45分、8時間を超える場合は少なくとも1時間の休憩を、労働時間の途中に与えなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-013", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、休日労働に対する割増賃金率は何%以上か。",
    choices: ["25%以上", "30%以上", "35%以上", "50%以上"],
    answer: 2,
    explanation: "労働基準法第37条により、法定休日に労働させた場合の割増賃金率は35%以上です。時間外労働は25%以上、深夜労働は25%以上です。",
    source: "hardcoded",
  },
  {
    id: "sh-014", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者は、労働者の国籍、信条又は社会的身分を理由として、賃金、労働時間その他の労働条件について、差別的取扱をしてはならない。",
    answer: true,
    explanation: "労働基準法第3条（均等待遇）により、国籍・信条・社会的身分を理由とする差別的取扱いは禁止されています。なお、性別による差別は男女雇用機会均等法で禁止されています。",
    source: "hardcoded",
  },
  {
    id: "sh-015", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、年次有給休暇の時効は何年か。",
    choices: ["1年", "2年", "3年", "5年"],
    answer: 1,
    explanation: "労働基準法第115条により、年次有給休暇の請求権は2年で時効消滅します。したがって、前年度に取得しなかった分は翌年度に繰り越すことができますが、2年で消滅します。",
    source: "hardcoded",
  },
  {
    id: "sh-016", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、年次有給休暇の付与日数について、継続勤務6年6ヶ月以上の場合の最大付与日数は何日か。",
    choices: ["15日", "18日", "20日", "25日"],
    answer: 2,
    explanation: "年次有給休暇は勤続年数に応じて増加し、6年6ヶ月以上で最大20日が付与されます。6ヶ月:10日、1年6ヶ月:11日、2年6ヶ月:12日、3年6ヶ月:14日、4年6ヶ月:16日、5年6ヶ月:18日、6年6ヶ月以上:20日です。",
    source: "hardcoded",
  },
  {
    id: "sh-017", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "使用者は、年10日以上の年次有給休暇が付与される労働者に対し、年5日について、時季を指定して取得させなければならない。",
    answer: true,
    explanation: "2019年4月施行の改正労働基準法により、年10日以上の年次有給休暇が付与される労働者に対して、使用者は年5日の年次有給休暇を確実に取得させなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-018", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、深夜業の時間帯はどれか。",
    choices: ["午後9時から午前5時", "午後10時から午前5時", "午後10時から午前6時", "午後11時から午前6時"],
    answer: 1,
    explanation: "労働基準法第37条第4項により、深夜業とは午後10時から午前5時までの間の労働をいいます。この時間帯に労働した場合、25%以上の割増賃金が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-019", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "月60時間を超える時間外労働の割増賃金率は何%以上か。",
    choices: ["25%以上", "35%以上", "50%以上", "60%以上"],
    answer: 2,
    explanation: "労働基準法第37条第1項ただし書により、1ヶ月60時間を超える時間外労働については50%以上の割増賃金率が適用されます。2023年4月からは中小企業にも適用されています。",
    source: "hardcoded",
  },
  {
    id: "sh-020", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者は、労働契約の不履行について違約金を定め、又は損害賠償額を予定する契約をしてはならない。",
    answer: true,
    explanation: "労働基準法第16条（賠償予定の禁止）により、違約金の定めや損害賠償額の予定は禁止されています。ただし、実際に発生した損害について賠償請求すること自体は禁止されていません。",
    source: "hardcoded",
  },
  {
    id: "sh-021", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者が労働者の貯蓄金を管理することについて正しいものはどれか。",
    choices: ["自由にできる", "労使協定を締結し届け出た場合に限り認められる", "全面的に禁止されている", "労働者の同意があればできる"],
    answer: 1,
    explanation: "労働基準法第18条により、使用者が労働者の貯蓄金を管理する（社内預金等）場合は、労使協定を締結し、行政官庁に届け出なければなりません。強制貯金は禁止されています。",
    source: "hardcoded",
  },
  {
    id: "sh-022", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、平均賃金の算定期間は、算定すべき事由の発生した日以前何ヶ月間か。",
    choices: ["1ヶ月間", "2ヶ月間", "3ヶ月間", "6ヶ月間"],
    answer: 2,
    explanation: "労働基準法第12条により、平均賃金は、算定すべき事由の発生した日以前3ヶ月間にその労働者に対し支払われた賃金の総額を、その期間の総日数で除して算定します。",
    source: "hardcoded",
  },
  {
    id: "sh-023", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者は、満18歳に満たない者を午後10時から午前5時までの間において使用してはならない。",
    answer: true,
    explanation: "労働基準法第61条により、使用者は満18歳に満たない年少者を深夜（午後10時〜午前5時）に使用してはなりません。ただし、交替制で使用する満16歳以上の男性等一部例外があります。",
    source: "hardcoded",
  },
  {
    id: "sh-024", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "1ヶ月単位の変形労働時間制を採用する場合、変形期間における法定労働時間の総枠の計算で、1週の法定労働時間として用いる時間数は何時間か。",
    choices: ["36時間", "38時間", "40時間", "44時間"],
    answer: 2,
    explanation: "1ヶ月単位の変形労働時間制では、変形期間の法定労働時間の総枠は「40時間×変形期間の暦日数÷7」で計算します。特例措置対象事業場では44時間で計算します。",
    source: "hardcoded",
  },
  {
    id: "sh-025", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "フレックスタイム制の清算期間の上限は何ヶ月か。",
    choices: ["1ヶ月", "2ヶ月", "3ヶ月", "6ヶ月"],
    answer: 2,
    explanation: "2019年4月の改正により、フレックスタイム制の清算期間の上限が1ヶ月から3ヶ月に延長されました。ただし、清算期間が1ヶ月を超える場合は労使協定を行政官庁に届け出る必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-026", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、労働条件の明示は口頭でもよい。",
    answer: false,
    explanation: "労働基準法第15条及び施行規則第5条により、賃金、労働時間等の主要な労働条件は書面（労働者が希望した場合はFAX・メール等も可）で明示しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-027", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、解雇予告の適用除外となる「試の使用期間中の者」の期間は何日か。",
    choices: ["7日", "14日", "30日", "60日"],
    answer: 1,
    explanation: "労働基準法第21条により、試の使用期間中の者は14日を超えて引き続き使用されるに至った場合を除き、解雇予告の規定は適用されません。14日以内であれば即日解雇が可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-028", type: "truefalse", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上、使用者は労働者に対して、前借金その他労働することを条件とする前貸の債権と賃金を相殺してはならない。",
    answer: true,
    explanation: "労働基準法第17条（前借金相殺の禁止）により、労働することを条件とする前貸の債権と賃金の相殺は禁止されています。これは労働者の身分拘束を防止する趣旨です。",
    source: "hardcoded",
  },
  {
    id: "sh-029", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法上の賃金の支払に関する時効は何年か（退職手当を除く）。",
    choices: ["1年", "2年", "3年", "5年"],
    answer: 2,
    explanation: "2020年4月の改正により、賃金請求権の消滅時効は当面の間3年とされています（将来的に5年に延長予定）。退職手当の時効は5年です。",
    source: "hardcoded",
  },
  {
    id: "sh-030", type: "choice", grade: 1, category: "labor-law" as SharoshiCategory,
    question: "労働基準法第1条に規定されている「労働条件の原則」として正しいものはどれか。",
    choices: ["労働条件は、使用者が決定する", "労働条件は、労働者と使用者が対等の立場において決定すべきものである", "労働条件は、行政官庁が決定する", "労働条件は、労働組合が決定する"],
    answer: 1,
    explanation: "労働基準法第2条第1項により、「労働条件は、労働者と使用者が、対等の立場において決定すべきものである」と規定されています。第1条では「労働条件は、労働者が人たるに値する生活を営むための必要を充たすべきものでなければならない」と定めています。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労働安全衛生法 (safety) — 30問
  // ==========================================================================
  {
    id: "sh-031", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、総括安全衛生管理者を選任しなければならない事業場の規模は、建設業の場合、常時何人以上か。",
    choices: ["50人以上", "100人以上", "300人以上", "1000人以上"],
    answer: 1,
    explanation: "建設業・運送業等は100人以上、製造業等は300人以上、その他は1000人以上で総括安全衛生管理者の選任が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-032", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "事業者は、常時50人以上の労働者を使用する事業場においては、衛生管理者を選任しなければならない。",
    answer: true,
    explanation: "労働安全衛生法第12条により、常時50人以上の労働者を使用する事業場では、衛生管理者を選任しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-033", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、産業医を選任しなければならない事業場の規模は常時何人以上か。",
    choices: ["10人以上", "30人以上", "50人以上", "100人以上"],
    answer: 2,
    explanation: "労働安全衛生法第13条により、常時50人以上の労働者を使用する事業場では産業医を選任しなければなりません。1000人以上では専属の産業医が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-034", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "一般健康診断の実施頻度は原則として何回か。",
    choices: ["6ヶ月に1回", "1年以内ごとに1回", "2年以内ごとに1回", "3年以内ごとに1回"],
    answer: 1,
    explanation: "労働安全衛生法第66条及び規則第44条により、1年以内ごとに1回の定期健康診断が義務です。特定業務従事者は6ヶ月以内ごとに1回です。",
    source: "hardcoded",
  },
  {
    id: "sh-035", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "安全委員会はすべての業種の50人以上の事業場で設置義務がある。",
    answer: false,
    explanation: "衛生委員会は全業種の50人以上で必要ですが、安全委員会は建設業、製造業等の一定の業種の50人以上の事業場に限られます。",
    source: "hardcoded",
  },
  {
    id: "sh-036", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "ストレスチェック制度の実施義務がある事業場の規模は常時何人以上か。",
    choices: ["10人以上", "30人以上", "50人以上", "100人以上"],
    answer: 2,
    explanation: "労働安全衛生法第66条の10により、常時50人以上の事業場で1年以内ごとに1回のストレスチェックが義務です。50人未満は努力義務です。",
    source: "hardcoded",
  },
  {
    id: "sh-037", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "事業者は、労働者を雇い入れたときは、安全又は衛生のための教育を行わなければならない。",
    answer: true,
    explanation: "労働安全衛生法第59条第1項により、雇入れ時の安全衛生教育が義務付けられています。作業内容変更時も同様です。",
    source: "hardcoded",
  },
  {
    id: "sh-038", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "安全管理者を選任しなければならない業種・規模の組合せとして正しいものはどれか。",
    choices: ["全業種・50人以上", "建設業等・50人以上", "全業種・100人以上", "製造業等・100人以上"],
    answer: 1,
    explanation: "安全管理者は、建設業、製造業、運送業等の一定の業種で、常時50人以上の労働者を使用する事業場で選任が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-039", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "衛生管理者の選任数について、常時200人を超え500人以下の事業場では何人以上か。",
    choices: ["1人以上", "2人以上", "3人以上", "4人以上"],
    answer: 1,
    explanation: "衛生管理者の選任数は、50人〜200人:1人、200人超〜500人:2人、500人超〜1000人:3人、1000人超〜2000人:4人、2000人超〜3000人:5人、3000人超:6人です。",
    source: "hardcoded",
  },
  {
    id: "sh-040", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "常時10人以上50人未満の労働者を使用する事業場では、安全衛生推進者又は衛生推進者を選任しなければならない。",
    answer: true,
    explanation: "労働安全衛生法第12条の2により、10人以上50人未満の事業場では安全衛生推進者（一定業種）又は衛生推進者（その他）の選任が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-041", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "作業主任者を選任しなければならない作業として、正しくないものはどれか。",
    choices: ["高圧室内作業", "酸素欠乏危険場所における作業", "一般事務作業", "有機溶剤を使用する作業"],
    answer: 2,
    explanation: "作業主任者は、高圧室内作業、酸素欠乏危険場所における作業、有機溶剤業務等の危険有害な作業について選任が必要です。一般事務作業は該当しません。",
    source: "hardcoded",
  },
  {
    id: "sh-042", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "特殊健康診断の対象となる有害業務に従事する労働者の健康診断の頻度は原則何回か。",
    choices: ["3ヶ月以内ごとに1回", "6ヶ月以内ごとに1回", "1年以内ごとに1回", "2年以内ごとに1回"],
    answer: 1,
    explanation: "有害業務に従事する労働者に対する特殊健康診断は、原則として6ヶ月以内ごとに1回実施しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-043", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "事業者は、健康診断の結果に基づき、健康診断個人票を作成して、これを5年間保存しなければならない。",
    answer: true,
    explanation: "労働安全衛生規則第51条により、事業者は一般健康診断の個人票を5年間保存しなければなりません。特殊健康診断はものによって保存期間が異なります。",
    source: "hardcoded",
  },
  {
    id: "sh-044", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、専属の産業医を選任しなければならない事業場の規模は常時何人以上か。",
    choices: ["500人以上", "1000人以上", "2000人以上", "3000人以上"],
    answer: 1,
    explanation: "常時1000人以上の労働者を使用する事業場、又は一定の有害業務に常時500人以上従事させる事業場では、専属の産業医を選任しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-045", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、安全衛生委員会の開催頻度は原則としてどれか。",
    choices: ["毎週1回", "毎月1回以上", "3ヶ月に1回以上", "半年に1回以上"],
    answer: 1,
    explanation: "安全委員会・衛生委員会（安全衛生委員会）は、毎月1回以上開催しなければなりません。委員会の議事概要は労働者に周知する必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-046", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "事業者は、労働災害が発生した場合、労働者が死亡し又は休業した場合には、遅滞なく労働者死傷病報告を所轄労働基準監督署長に提出しなければならない。",
    answer: true,
    explanation: "労働安全衛生規則第97条により、労働者が死亡し又は休業した場合には労働者死傷病報告の提出が必要です。休業4日未満は四半期ごとにまとめて提出することもできます。",
    source: "hardcoded",
  },
  {
    id: "sh-047", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、事業者が作成すべき「安全衛生管理体制」に関する計画を何というか。",
    choices: ["安全衛生計画", "安全衛生方針", "安全衛生管理計画", "事業者行動計画"],
    answer: 0,
    explanation: "事業者は安全衛生に関する計画（安全衛生計画）を作成し、労働災害の防止に努める必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-048", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、元方事業者が統括安全衛生責任者を選任すべき建設業の工事現場の規模は、常時何人以上か（ずい道等を除く）。",
    choices: ["20人以上", "30人以上", "50人以上", "100人以上"],
    answer: 2,
    explanation: "建設業では常時50人以上（ずい道等の建設工事は30人以上）の労働者を使用する場合、統括安全衛生責任者を選任しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-049", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "長時間労働者に対する面接指導は、時間外・休日労働が1月当たり80時間を超え、かつ疲労の蓄積が認められる者が申し出た場合に実施する。",
    answer: true,
    explanation: "労働安全衛生法第66条の8により、時間外・休日労働が月80時間超で疲労の蓄積がある労働者からの申出があった場合、医師による面接指導を実施しなければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-050", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "労働安全衛生法上、事業者が講ずべき措置として「機械等による危険の防止」が規定されているのは第何条か。",
    choices: ["第20条", "第22条", "第25条", "第28条"],
    answer: 0,
    explanation: "労働安全衛生法第20条で機械等による危険防止、第21条で墜落・崩壊等の防止、第22条で健康障害の防止が規定されています。",
    source: "hardcoded",
  },
  {
    id: "sh-051", type: "choice", grade: 1, category: "safety" as SharoshiCategory,
    question: "新規化学物質を製造し又は輸入しようとする事業者は、あらかじめ何を届け出なければならないか。",
    choices: ["安全データシート", "有害性の調査結果", "化学物質管理計画", "リスクアセスメント結果"],
    answer: 1,
    explanation: "労働安全衛生法第57条の3により、新規化学物質の製造・輸入者は、あらかじめ有害性の調査を行い、その結果を厚生労働大臣に届け出なければなりません。",
    source: "hardcoded",
  },
  {
    id: "sh-052", type: "truefalse", grade: 1, category: "safety" as SharoshiCategory,
    question: "リスクアセスメントとは、職場における危険性又は有害性等の調査及びその結果に基づく措置のことである。",
    answer: true,
    explanation: "労働安全衛生法第28条の2により、事業者は、建設物、設備、原材料等の危険性又は有害性等を調査し、その結果に基づいて必要な措置を講ずるよう努めなければなりません。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労災保険法 (workers-comp) — 30問
  // ==========================================================================
  {
    id: "sh-053", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の休業補償給付の支給額は、休業1日につき給付基礎日額の何%相当額か。",
    choices: ["40%", "50%", "60%", "80%"],
    answer: 2,
    explanation: "休業補償給付は給付基礎日額の60%です。休業特別支給金20%と合わせて実質80%の補償を受けられます。",
    source: "hardcoded",
  },
  {
    id: "sh-054", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の休業補償給付は、休業開始から何日目から支給されるか。",
    choices: ["初日から", "2日目から", "4日目から", "8日目から"],
    answer: 2,
    explanation: "休業補償給付は休業4日目から支給されます。最初の3日間（待期期間）は事業主が労基法に基づく休業補償（平均賃金の60%）を行います。",
    source: "hardcoded",
  },
  {
    id: "sh-055", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "通勤災害は、労災保険の保護の対象である。",
    answer: true,
    explanation: "労災保険法第7条により、通勤災害も労災保険の保護対象です。住居と就業場所の往復等を合理的な経路・方法で行うことが要件です。",
    source: "hardcoded",
  },
  {
    id: "sh-056", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "遺族補償年金の最先順位者はどれか。",
    choices: ["労働者の子", "労働者の配偶者（事実婚含む）", "労働者の父母", "労働者の孫"],
    answer: 1,
    explanation: "遺族補償年金の受給資格者の順位は、(1)配偶者、(2)子、(3)父母、(4)孫、(5)祖父母、(6)兄弟姉妹です。",
    source: "hardcoded",
  },
  {
    id: "sh-057", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "障害補償年金は、障害等級第何級以上の場合に支給されるか。",
    choices: ["第3級以上", "第5級以上", "第7級以上", "第10級以上"],
    answer: 2,
    explanation: "障害補償年金は第1級〜第7級、障害補償一時金は第8級〜第14級に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-058", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険は、原則として労働者を使用するすべての事業に適用され、保険料は全額事業主が負担する。",
    answer: true,
    explanation: "労災保険は全額事業主負担です。健康保険や厚生年金（労使折半）とは異なります。",
    source: "hardcoded",
  },
  {
    id: "sh-059", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "傷病補償年金は、療養開始後何年何ヶ月を経過しても治らない場合に支給されうるか。",
    choices: ["6ヶ月", "1年", "1年6ヶ月", "3年"],
    answer: 2,
    explanation: "傷病補償年金は、療養開始後1年6ヶ月を経過した日以後において、傷病が治っておらず傷病等級第1級〜第3級に該当する場合に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-060", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の葬祭料（葬祭給付）の額として正しいものはどれか。",
    choices: ["給付基礎日額の30日分", "315,000円に給付基礎日額の30日分を加えた額等", "給付基礎日額の60日分", "一律50万円"],
    answer: 1,
    explanation: "葬祭料は、315,000円に給付基礎日額の30日分を加えた額、又は給付基礎日額の60日分のいずれか高い方が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-061", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の療養補償給付は、治療費の自己負担なく支給される（労災指定病院の場合）。",
    answer: true,
    explanation: "労災指定病院で療養する場合は現物給付（療養の給付）として自己負担なく治療を受けられます。指定病院以外では療養の費用として後から支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-062", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険のメリット制について、継続事業の場合、連続する何年間の収支率に基づいて保険料率が増減されるか。",
    choices: ["1年間", "2年間", "3年間", "5年間"],
    answer: 2,
    explanation: "メリット制は、連続する3保険年度の収支率に基づいて、事業の種類ごとに定められた労災保険率を±40%の範囲で増減させる制度です。",
    source: "hardcoded",
  },
  {
    id: "sh-063", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "特別加入制度の対象者として正しくないものはどれか。",
    choices: ["中小事業主", "一人親方等", "海外派遣者", "大企業の役員"],
    answer: 3,
    explanation: "特別加入は、中小事業主等、一人親方等、特定作業従事者、海外派遣者が対象です。大企業の役員は対象外です。",
    source: "hardcoded",
  },
  {
    id: "sh-064", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "業務災害の認定には、業務遂行性と業務起因性の両方が必要である。",
    answer: true,
    explanation: "業務災害と認定されるためには、(1)事業主の支配下にあること（業務遂行性）、(2)業務と傷病等との間に因果関係があること（業務起因性）の両方が必要です。",
    source: "hardcoded",
  },
  {
    id: "sh-065", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "通勤災害における「通勤」の定義として、逸脱又は中断をした場合、原則としてその後の移動はどうなるか。",
    choices: ["通勤と認められる", "通勤と認められない", "使用者の承認があれば認められる", "労基署の判断による"],
    answer: 1,
    explanation: "通勤経路を逸脱又は中断した場合、逸脱・中断中及びその後の移動は原則として通勤と認められません。ただし、日用品の購入等の日常生活上必要な行為については、逸脱・中断後に合理的な経路に復した後は通勤と認められます。",
    source: "hardcoded",
  },
  {
    id: "sh-066", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の介護補償給付の支給要件として、障害補償年金又は傷病補償年金の受給者で、障害等級・傷病等級が何級以上であることが必要か。",
    choices: ["第1級のみ", "第2級以上", "第3級以上", "第5級以上"],
    answer: 1,
    explanation: "介護補償給付は、障害補償年金又は傷病補償年金の第1級又は第2級の受給者で、現に介護を受けている場合に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-067", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険給付を受ける権利は、譲り渡し、担保に供し、又は差し押さえることができない。",
    answer: true,
    explanation: "労災保険法第12条の5により、保険給付を受ける権利は譲渡・担保提供・差押えが禁止されています。労働者保護の観点からの規定です。",
    source: "hardcoded",
  },
  {
    id: "sh-068", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険の保険給付の請求の時効として、療養補償給付（療養の費用）の時効は何年か。",
    choices: ["1年", "2年", "3年", "5年"],
    answer: 1,
    explanation: "療養補償給付（費用請求）、休業補償給付、葬祭料、介護補償給付の時効は2年です。障害補償給付、遺族補償給付の時効は5年です。",
    source: "hardcoded",
  },
  {
    id: "sh-069", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険法上の「給付基礎日額」は、原則として何に基づいて算定されるか。",
    choices: ["標準報酬月額", "労基法の平均賃金", "所定内給与", "基本給"],
    answer: 1,
    explanation: "給付基礎日額は、原則として労働基準法第12条の平均賃金に相当する額です。算定事由発生日以前3ヶ月間の賃金総額をその期間の総日数で除して算定します。",
    source: "hardcoded",
  },
  {
    id: "sh-070", type: "truefalse", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "二次健康診断等給付は、一次健康診断で脳・心臓疾患に関する一定の異常所見が認められた場合に支給される。",
    answer: true,
    explanation: "二次健康診断等給付は、定期健康診断等（一次健康診断）で血圧、血中脂質、血糖、腹囲又はBMIの4つの検査項目すべてに異常の所見があると認められた場合に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-071", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "遺族補償一時金が支給されるのはどのような場合か。",
    choices: ["遺族補償年金の受給資格者がいる場合", "遺族補償年金の受給資格者がいない場合等", "労働者が希望した場合", "事業主が申請した場合"],
    answer: 1,
    explanation: "遺族補償一時金は、(1)遺族補償年金の受給資格者がいない場合、又は(2)遺族補償年金の受給権者が失権し他に受給資格者がいない場合に、既支給額との差額として支給されます。額は給付基礎日額の1000日分です。",
    source: "hardcoded",
  },
  {
    id: "sh-072", type: "choice", grade: 1, category: "workers-comp" as SharoshiCategory,
    question: "労災保険法上、中小事業主の特別加入で、金融業の場合の事業主の規模要件は常時何人以下か。",
    choices: ["20人以下", "50人以下", "100人以下", "300人以下"],
    answer: 1,
    explanation: "中小事業主の特別加入の規模要件は、金融・保険・不動産・小売業は50人以下、卸売・サービス業は100人以下、その他は300人以下です。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 雇用保険法 (employment-ins) — 30問
  // ==========================================================================
  {
    id: "sh-073", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の基本手当の受給資格を得るには、原則として離職の日以前何年間に被保険者期間が何ヶ月以上必要か。",
    choices: ["1年間に6ヶ月以上", "2年間に12ヶ月以上", "2年間に6ヶ月以上", "1年間に12ヶ月以上"],
    answer: 1,
    explanation: "原則として離職前2年間に被保険者期間が12ヶ月以上必要です。特定受給資格者等は離職前1年間に6ヶ月以上で足ります。",
    source: "hardcoded",
  },
  {
    id: "sh-074", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の基本手当の待期期間は何日間か。",
    choices: ["3日間", "7日間", "14日間", "30日間"],
    answer: 1,
    explanation: "基本手当は求職申込後、失業状態が通算7日間（待期期間）経過するまで支給されません。自己都合退職はさらに給付制限期間があります。",
    source: "hardcoded",
  },
  {
    id: "sh-075", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "基本手当の日額は、原則として賃金日額の何%〜何%か。",
    choices: ["40%〜60%", "45%〜80%", "50%〜80%", "60%〜90%"],
    answer: 2,
    explanation: "基本手当の日額は賃金日額の50%〜80%です。賃金が低い人ほど高い率が適用されます。60歳以上65歳未満は45%〜80%です。",
    source: "hardcoded",
  },
  {
    id: "sh-076", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の被保険者には、一般被保険者、高年齢被保険者、短期雇用特例被保険者、日雇労働被保険者の4種類がある。",
    answer: true,
    explanation: "雇用保険の被保険者は4種類です。65歳以上は高年齢被保険者、季節的雇用者は短期雇用特例被保険者、日雇労働者は日雇労働被保険者、それ以外は一般被保険者です。",
    source: "hardcoded",
  },
  {
    id: "sh-077", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "育児休業給付金は、休業開始から180日目までは賃金日額の何%か。",
    choices: ["50%", "60%", "67%", "80%"],
    answer: 2,
    explanation: "育児休業給付金は、180日目までは67%、181日目以降は50%が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-078", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "自己都合退職の場合の給付制限期間は、原則として待期期間満了後何ヶ月か（5年間で2回目まで）。",
    choices: ["1ヶ月", "2ヶ月", "3ヶ月", "6ヶ月"],
    answer: 1,
    explanation: "2020年10月の改正により、5年間のうち2回までは給付制限期間が2ヶ月に短縮されました。3回目以降は3ヶ月です。",
    source: "hardcoded",
  },
  {
    id: "sh-079", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "教育訓練給付金は、一定の教育訓練の費用の一部が支給される制度である。",
    answer: true,
    explanation: "一般教育訓練は費用の20%（最大10万円）、専門実践教育訓練は最大70%が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-080", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "一般被保険者の所定給付日数（基本手当）で、自己都合退職・被保険者期間10年以上20年未満の場合は何日か。",
    choices: ["90日", "120日", "150日", "180日"],
    answer: 1,
    explanation: "自己都合退職の所定給付日数は、被保険者期間10年未満:90日、10年以上20年未満:120日、20年以上:150日です。",
    source: "hardcoded",
  },
  {
    id: "sh-081", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の適用事業に該当しないものはどれか。",
    choices: ["農林水産業の個人経営で常時5人未満の事業", "株式会社", "国の機関", "地方公共団体"],
    answer: 0,
    explanation: "雇用保険は原則としてすべての事業に適用されますが、農林水産業の個人経営で常時5人未満の労働者を雇用する事業は暫定任意適用事業となります。",
    source: "hardcoded",
  },
  {
    id: "sh-082", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険の被保険者となる要件として、1週間の所定労働時間が20時間以上であることが必要である。",
    answer: true,
    explanation: "雇用保険の被保険者となるには、(1)1週間の所定労働時間が20時間以上、(2)31日以上引き続き雇用されることが見込まれることが要件です。",
    source: "hardcoded",
  },
  {
    id: "sh-083", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "高年齢求職者給付金は、一般被保険者の基本手当に相当する給付として何に支給されるか。",
    choices: ["一般被保険者", "高年齢被保険者", "短期雇用特例被保険者", "日雇労働被保険者"],
    answer: 1,
    explanation: "高年齢求職者給付金は、65歳以上の高年齢被保険者が失業した場合に、被保険者期間に応じて30日分又は50日分の一時金として支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-084", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "再就職手当の支給要件として、基本手当の支給残日数が所定給付日数の何分の1以上必要か。",
    choices: ["4分の1以上", "3分の1以上", "2分の1以上", "3分の2以上"],
    answer: 1,
    explanation: "再就職手当は、基本手当の支給残日数が所定給付日数の3分の1以上残っている場合に支給されます。残日数3分の2以上なら70%、3分の1以上なら60%の給付です。",
    source: "hardcoded",
  },
  {
    id: "sh-085", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "介護休業給付金は、対象家族1人につき通算93日を限度に、3回まで分割して取得できる。",
    answer: true,
    explanation: "介護休業給付金は、対象家族1人につき通算93日を限度に、3回まで分割取得が可能です。支給額は休業開始時賃金日額の67%です。",
    source: "hardcoded",
  },
  {
    id: "sh-086", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "特定受給資格者（会社都合退職等）で、被保険者期間5年以上10年未満、45歳以上60歳未満の場合の所定給付日数は何日か。",
    choices: ["180日", "240日", "270日", "330日"],
    answer: 1,
    explanation: "特定受給資格者は自己都合退職者より手厚い給付日数が設定されています。この条件では240日です。年齢と被保険者期間により90日〜330日の範囲です。",
    source: "hardcoded",
  },
  {
    id: "sh-087", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険料率のうち、失業等給付に係る保険料は労使でどのように負担するか。",
    choices: ["全額事業主負担", "事業主2：労働者1", "労使折半", "全額労働者負担"],
    answer: 2,
    explanation: "失業等給付に係る保険料は労使折半です。ただし、雇用保険二事業（雇用安定事業・能力開発事業）に係る保険料は全額事業主負担です。",
    source: "hardcoded",
  },
  {
    id: "sh-088", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "基本手当を受給するためには、ハローワークに出頭し、求職の申込みをしなければならない。",
    answer: true,
    explanation: "基本手当を受給するには、離職後、管轄のハローワーク（公共職業安定所）に出頭し、求職の申込みをしたうえで、失業の認定を受ける必要があります。",
    source: "hardcoded",
  },
  {
    id: "sh-089", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "専門実践教育訓練給付金の支給率は、受講費用の何%か（上限あり）。",
    choices: ["20%", "40%", "50%", "70%"],
    answer: 2,
    explanation: "専門実践教育訓練給付金は受講費用の50%（年間上限40万円）です。資格取得等して就職した場合はさらに20%が追加支給され、合計70%（年間上限56万円）となります。",
    source: "hardcoded",
  },
  {
    id: "sh-090", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "就業促進定着手当は、再就職手当を受けた者が再就職先に何ヶ月以上雇用された場合に支給されうるか。",
    choices: ["3ヶ月以上", "6ヶ月以上", "1年以上", "2年以上"],
    answer: 1,
    explanation: "就業促進定着手当は、再就職手当を受けた者が再就職先に6ヶ月以上雇用され、再就職後の賃金が離職前の賃金より低い場合に、その差額の6ヶ月分が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-091", type: "truefalse", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用保険法上、失業の認定は原則として4週間に1回行われる。",
    answer: true,
    explanation: "失業の認定は、原則として4週間に1回（28日ごと）、受給資格者がハローワークに出頭して行います。認定日にはその前の4週間の求職活動実績が確認されます。",
    source: "hardcoded",
  },
  {
    id: "sh-092", type: "choice", grade: 1, category: "employment-ins" as SharoshiCategory,
    question: "雇用継続給付のうち、高年齢雇用継続基本給付金が支給されるのは何歳から何歳までの被保険者か。",
    choices: ["55歳から60歳まで", "60歳から65歳まで", "60歳から70歳まで", "65歳から70歳まで"],
    answer: 1,
    explanation: "高年齢雇用継続基本給付金は、60歳以上65歳未満の被保険者で、60歳時点に比べて賃金が75%未満に低下した場合に支給されます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 健康保険法 (health-ins) — 30問
  // ==========================================================================
  {
    id: "sh-093", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の被保険者の一部負担金は、70歳未満で何割か。",
    choices: ["1割", "2割", "3割", "5割"],
    answer: 2,
    explanation: "70歳未満は3割、70歳以上75歳未満は原則2割（現役並み所得者は3割）、小学校就学前は2割です。",
    source: "hardcoded",
  },
  {
    id: "sh-094", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "傷病手当金は、連続3日間の待期期間の後、何日目から支給されるか。",
    choices: ["2日目", "4日目", "8日目", "15日目"],
    answer: 1,
    explanation: "傷病手当金は、連続する3日間の待期期間を経て4日目から支給されます。待期期間には有給休暇や休日も含まれます。",
    source: "hardcoded",
  },
  {
    id: "sh-095", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "傷病手当金の支給期間は、支給開始日から通算して最長何年間か。",
    choices: ["6ヶ月", "1年", "1年6ヶ月", "3年"],
    answer: 2,
    explanation: "2022年1月改正により、支給開始日から通算して1年6ヶ月です。出勤した期間は通算されません。",
    source: "hardcoded",
  },
  {
    id: "sh-096", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "被扶養者の年間収入要件は130万円未満である（60歳未満の場合）。",
    answer: true,
    explanation: "被扶養者の収入要件は年間130万円未満（60歳以上又は障害者は180万円未満）かつ被保険者の年間収入の2分の1未満です。",
    source: "hardcoded",
  },
  {
    id: "sh-097", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "出産手当金の支給期間はどれか。",
    choices: ["産前42日・産後42日", "産前42日・産後56日", "産前56日・産後56日", "産前56日・産後42日"],
    answer: 1,
    explanation: "出産手当金は産前42日（多胎98日）から産後56日までです。",
    source: "hardcoded",
  },
  {
    id: "sh-098", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "出産育児一時金の額は1児につきいくらか（2023年4月以降）。",
    choices: ["30万円", "42万円", "50万円", "55万円"],
    answer: 2,
    explanation: "2023年4月の改正により、出産育児一時金は1児につき50万円に引き上げられました。",
    source: "hardcoded",
  },
  {
    id: "sh-099", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の保険料は、事業主と被保険者が折半して負担する。",
    answer: true,
    explanation: "健保法第161条により原則折半です。健康保険組合は規約で事業主負担を増加させることが可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-100", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "傷病手当金の支給額は、1日につき標準報酬日額の何分のいくつか。",
    choices: ["2分の1", "3分の2", "4分の3", "10分の6"],
    answer: 1,
    explanation: "傷病手当金は、1日につき支給開始日以前の継続した12ヶ月間の各月の標準報酬月額の平均額の30分の1の3分の2に相当する額が支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-101", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の任意継続被保険者の加入期間は最長何年か。",
    choices: ["6ヶ月", "1年", "2年", "3年"],
    answer: 2,
    explanation: "任意継続被保険者は退職後も最長2年間、健康保険に加入できます。要件は、資格喪失日の前日までに継続して2ヶ月以上被保険者であったことです。",
    source: "hardcoded",
  },
  {
    id: "sh-102", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の埋葬料は、被保険者が死亡した場合に、埋葬を行う者に対して5万円が支給される。",
    answer: true,
    explanation: "健保法第100条により、被保険者が死亡した場合、埋葬を行う者に対して5万円の埋葬料が支給されます。被扶養者が死亡した場合は家族埋葬料として同額が被保険者に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-103", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "高額療養費制度における、70歳未満で一般所得者の自己負担限度額の計算式はどれか（月額）。",
    choices: ["57,600円", "80,100円＋（医療費−267,000円）×1%", "167,400円＋（医療費−558,000円）×1%", "35,400円"],
    answer: 1,
    explanation: "70歳未満の一般所得者（年収約370万〜約770万円）の自己負担限度額は「80,100円＋（医療費−267,000円）×1%」です。多数回該当は44,400円です。",
    source: "hardcoded",
  },
  {
    id: "sh-104", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の標準報酬月額の等級数はいくつか。",
    choices: ["30等級", "47等級", "50等級", "62等級"],
    answer: 2,
    explanation: "健康保険の標準報酬月額は、第1級（58,000円）から第50級（1,390,000円）までの50等級に区分されています。",
    source: "hardcoded",
  },
  {
    id: "sh-105", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "全国健康保険協会（協会けんぽ）の保険料率は、都道府県ごとに異なる。",
    answer: true,
    explanation: "協会けんぽの保険料率は、都道府県ごとの医療費の実績に基づき異なる料率が設定されています。2023年度は約9.3%〜10.7%の範囲です。",
    source: "hardcoded",
  },
  {
    id: "sh-106", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険法上、標準報酬月額の定時決定は何月に行われるか。",
    choices: ["3月", "4月", "7月", "10月"],
    answer: 2,
    explanation: "定時決定は、毎年7月1日現在のすべての被保険者について、4月・5月・6月の3ヶ月間の報酬の平均額により標準報酬月額を決定するものです。9月から翌年8月まで適用されます。",
    source: "hardcoded",
  },
  {
    id: "sh-107", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "随時改定（月額変更届）が行われる要件として、固定的賃金の変動後何ヶ月間の報酬の平均が従前と2等級以上の差がある場合か。",
    choices: ["1ヶ月間", "2ヶ月間", "3ヶ月間", "6ヶ月間"],
    answer: 2,
    explanation: "随時改定は、固定的賃金が変動し、変動月以後3ヶ月間の報酬の平均額が従前の標準報酬月額と2等級以上の差がある場合に行われます。",
    source: "hardcoded",
  },
  {
    id: "sh-108", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の被保険者は、適用事業所に使用される者及び任意継続被保険者である。",
    answer: true,
    explanation: "健保法第3条により、被保険者は(1)適用事業所に使用される者、(2)任意継続被保険者に大別されます。日雇特例被保険者も含まれます。",
    source: "hardcoded",
  },
  {
    id: "sh-109", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の標準賞与額の上限は、年度の累計でいくらか。",
    choices: ["150万円", "540万円", "573万円", "上限なし"],
    answer: 2,
    explanation: "健康保険の標準賞与額は、年度（4月〜翌3月）の累計で573万円が上限です。なお、厚生年金の標準賞与額は1回の支給につき150万円が上限です。",
    source: "hardcoded",
  },
  {
    id: "sh-110", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の適用事業所の要件として、法人の事業所は従業員何人から強制適用か。",
    choices: ["1人以上（全法人）", "5人以上", "10人以上", "常時使用する者の数にかかわらない"],
    answer: 0,
    explanation: "法人の事業所は、従業員の数にかかわらず、すべて強制適用事業所となります。個人事業は常時5人以上（一定の業種）で強制適用です。",
    source: "hardcoded",
  },
  {
    id: "sh-111", type: "truefalse", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "健康保険の保険給付には、療養の給付、傷病手当金、出産手当金、出産育児一時金、埋葬料等がある。",
    answer: true,
    explanation: "健康保険の主な保険給付は、療養の給付（医療費の7割給付）、傷病手当金、出産手当金、出産育児一時金、埋葬料、高額療養費等があります。",
    source: "hardcoded",
  },
  {
    id: "sh-112", type: "choice", grade: 1, category: "health-ins" as SharoshiCategory,
    question: "資格喪失後の傷病手当金の継続給付を受けるための要件として、資格喪失日の前日までに継続して何ヶ月以上被保険者であったことが必要か。",
    choices: ["6ヶ月以上", "1年以上", "2年以上", "3年以上"],
    answer: 1,
    explanation: "資格喪失後の傷病手当金の継続給付は、資格喪失日の前日までに継続して1年以上被保険者であった者が、資格喪失時に傷病手当金を受けていたか受けられる状態にあった場合に認められます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 年金法 (pension) — 30問
  // ==========================================================================
  {
    id: "sh-113", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "国民年金の第1号被保険者とはどれか。",
    choices: ["会社員や公務員", "20歳以上60歳未満の自営業者・学生等", "第2号被保険者の被扶養配偶者", "65歳以上の年金受給者"],
    answer: 1,
    explanation: "第1号被保険者は、日本国内に住所を有する20歳以上60歳未満の者で、第2号・第3号以外の者（自営業者、学生等）です。",
    source: "hardcoded",
  },
  {
    id: "sh-114", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の受給資格期間は原則何年以上か。",
    choices: ["10年以上", "15年以上", "20年以上", "25年以上"],
    answer: 0,
    explanation: "2017年8月の改正により25年から10年に短縮されました。",
    source: "hardcoded",
  },
  {
    id: "sh-115", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の支給開始年齢は原則何歳か。",
    choices: ["60歳", "62歳", "65歳", "70歳"],
    answer: 2,
    explanation: "原則65歳です。繰上げ（60歳〜）は減額、繰下げ（66歳〜75歳）は増額されます。",
    source: "hardcoded",
  },
  {
    id: "sh-116", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の繰下げ受給は、1ヶ月当たり0.7%増額される。",
    answer: true,
    explanation: "1ヶ月0.7%増額で、最大75歳まで繰り下げると84%増額（0.7%×120ヶ月）となります。",
    source: "hardcoded",
  },
  {
    id: "sh-117", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "厚生年金保険の保険料率は何%か。",
    choices: ["8.914%", "16.058%", "18.3%", "20.0%"],
    answer: 2,
    explanation: "厚生年金保険料率は18.3%（2017年9月以降固定）で、労使折半（各9.15%）です。",
    source: "hardcoded",
  },
  {
    id: "sh-118", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "遺族基礎年金を受給できる遺族はどれか。",
    choices: ["配偶者のみ", "子のある配偶者又は子", "父母又は祖父母", "すべての遺族"],
    answer: 1,
    explanation: "遺族基礎年金は「子のある配偶者」又は「子」に支給されます。子とは18歳到達年度末までの子等です。",
    source: "hardcoded",
  },
  {
    id: "sh-119", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "障害基礎年金は障害等級1級又は2級に該当する場合に支給される。3級は対象外である。",
    answer: true,
    explanation: "障害基礎年金は1級・2級のみです。3級は厚生年金の障害厚生年金として支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-120", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "老齢基礎年金の繰上げ受給の減額率は、1ヶ月当たり何%か（1962年4月2日以後生まれ）。",
    choices: ["0.4%", "0.5%", "0.7%", "1.0%"],
    answer: 0,
    explanation: "2022年4月の改正により、1962年4月2日以後生まれの者の繰上げ減額率は1ヶ月当たり0.4%です。60歳で繰り上げると24%減額（0.4%×60ヶ月）となります。それ以前生まれの者は0.5%です。",
    source: "hardcoded",
  },
  {
    id: "sh-121", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "国民年金の保険料免除制度で、全額免除された期間の老齢基礎年金額への反映割合はどれか（国庫負担2分の1の場合）。",
    choices: ["0（反映なし）", "4分の1", "2分の1", "4分の3"],
    answer: 2,
    explanation: "全額免除期間は年金額の2分の1（国庫負担分）が反映されます。4分の3免除は8分の5、半額免除は8分の6、4分の1免除は8分の7が反映されます。",
    source: "hardcoded",
  },
  {
    id: "sh-122", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "学生納付特例制度は、20歳以上の学生が国民年金保険料の納付を猶予される制度であり、猶予された期間は受給資格期間に算入される。",
    answer: true,
    explanation: "学生納付特例期間は受給資格期間には算入されますが、年金額の計算には反映されません。10年以内に追納すれば年金額に反映されます。",
    source: "hardcoded",
  },
  {
    id: "sh-123", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "厚生年金保険の被保険者の年齢の上限は原則何歳か。",
    choices: ["60歳", "65歳", "70歳", "75歳"],
    answer: 2,
    explanation: "厚生年金保険の被保険者は原則70歳未満の者です。70歳以上でも老齢年金の受給資格期間を満たしていない場合は高齢任意加入が可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-124", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "在職老齢年金制度において、65歳以上の場合、賃金と年金の合計が月額いくらを超えると年金が支給停止されるか（2022年4月以降）。",
    choices: ["28万円", "47万円", "48万円", "50万円"],
    answer: 2,
    explanation: "2022年4月の改正により、65歳以上の在職老齢年金の支給停止基準額は48万円に統一されました（それ以前は47万円）。賃金と年金の合計が48万円を超えると、超えた額の2分の1が支給停止されます。",
    source: "hardcoded",
  },
  {
    id: "sh-125", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "障害基礎年金の1級の額は、2級の額の1.25倍である。",
    answer: true,
    explanation: "障害基礎年金の1級の額は、2級の額（老齢基礎年金の満額と同額）の1.25倍に相当する額です。",
    source: "hardcoded",
  },
  {
    id: "sh-126", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "遺族厚生年金の額は、死亡した者の老齢厚生年金の報酬比例部分の何分のいくつか。",
    choices: ["2分の1", "3分の2", "4分の3", "5分の4"],
    answer: 2,
    explanation: "遺族厚生年金の額は、死亡した者の老齢厚生年金の報酬比例部分の4分の3に相当する額です。",
    source: "hardcoded",
  },
  {
    id: "sh-127", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "国民年金の付加保険料は月額いくらか。",
    choices: ["200円", "400円", "600円", "1,000円"],
    answer: 1,
    explanation: "付加保険料は月額400円です。付加年金の額は「200円×付加保険料納付月数」で計算され、2年で元が取れる仕組みです。",
    source: "hardcoded",
  },
  {
    id: "sh-128", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "第3号被保険者は、第2号被保険者の被扶養配偶者であり、20歳以上60歳未満の者である。保険料は自分で納付する必要がない。",
    answer: true,
    explanation: "第3号被保険者の保険料は、配偶者が加入する厚生年金・共済組合の制度全体で負担するため、個別に保険料を納付する必要はありません。",
    source: "hardcoded",
  },
  {
    id: "sh-129", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "厚生年金保険の標準報酬月額の等級数はいくつか。",
    choices: ["30等級", "32等級", "47等級", "50等級"],
    answer: 1,
    explanation: "厚生年金保険の標準報酬月額は、第1級（88,000円）から第32級（650,000円）までの32等級に区分されています。健康保険の50等級とは異なります。",
    source: "hardcoded",
  },
  {
    id: "sh-130", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "寡婦年金が支給される要件として、夫の第1号被保険者としての保険料納付済期間と保険料免除期間を合算して何年以上必要か。",
    choices: ["5年以上", "10年以上", "15年以上", "25年以上"],
    answer: 1,
    explanation: "寡婦年金は、第1号被保険者としての保険料納付済期間と免除期間の合計が10年以上ある夫が死亡した場合に、10年以上婚姻関係にあった妻に60歳から65歳まで支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-131", type: "truefalse", grade: 1, category: "pension" as SharoshiCategory,
    question: "老齢厚生年金には、加給年金額が加算される場合がある。加給年金額は、受給権者に生計を維持されている65歳未満の配偶者又は一定の子がいる場合に加算される。",
    answer: true,
    explanation: "老齢厚生年金の受給権者で、厚生年金被保険者期間が20年以上ある者に、65歳未満の配偶者又は18歳到達年度末までの子（障害のある子は20歳未満）がいる場合に加給年金額が加算されます。",
    source: "hardcoded",
  },
  {
    id: "sh-132", type: "choice", grade: 1, category: "pension" as SharoshiCategory,
    question: "国民年金の保険料の追納ができる期間は、免除等の承認を受けた期間の翌年度から起算して何年以内か。",
    choices: ["2年以内", "5年以内", "10年以内", "制限なし"],
    answer: 2,
    explanation: "保険料の追納は、免除等の承認を受けた期間の翌年度から起算して10年以内に行うことができます。3年度目以降は当時の保険料に加算額が付きます。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 労務管理その他の労働に関する一般常識 (general-labor) — 30問
  // ==========================================================================
  {
    id: "sh-133", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働契約法上、就業規則の不利益変更は原則としてどうか。",
    choices: ["自由にできる", "労基署の許可があればできる", "できない", "合理的理由があればできる"],
    answer: 2,
    explanation: "労働契約法第9条により、労働者と合意することなく就業規則による不利益変更はできません。ただし第10条で合理的な変更の例外があります。",
    source: "hardcoded",
  },
  {
    id: "sh-134", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "最低賃金の種類として正しいものはどれか。",
    choices: ["全国最低賃金と都道府県最低賃金", "地域別最低賃金と特定最低賃金", "基本最低賃金と特別最低賃金", "法定最低賃金と協定最低賃金"],
    answer: 1,
    explanation: "最低賃金には「地域別最低賃金」と「特定最低賃金（産業別最低賃金）」の2種類があります。",
    source: "hardcoded",
  },
  {
    id: "sh-135", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "男女雇用機会均等法は、募集・採用、配置・昇進等における性別を理由とする差別を禁止している。",
    answer: true,
    explanation: "均等法第5条・第6条により、性別を理由とする差別的取扱いは禁止されています。",
    source: "hardcoded",
  },
  {
    id: "sh-136", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "育児休業は原則として子が何歳に達するまで取得できるか。",
    choices: ["6ヶ月", "1歳", "1歳6ヶ月", "3歳"],
    answer: 1,
    explanation: "原則1歳まで。保育所に入れない等の場合は1歳6ヶ月、再延長で2歳まで延長可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-137", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働者派遣の同一組織単位での受入期間の上限は何年か。",
    choices: ["1年", "2年", "3年", "5年"],
    answer: 2,
    explanation: "同一組織単位での同一の派遣労働者の受入れは3年が上限です。",
    source: "hardcoded",
  },
  {
    id: "sh-138", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "パートタイム・有期雇用労働法は、いわゆる「同一労働同一賃金」の原則を定めている。",
    answer: true,
    explanation: "パートタイム・有期雇用労働法第8条・第9条により、不合理な待遇差が禁止されています。",
    source: "hardcoded",
  },
  {
    id: "sh-139", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働組合法上、使用者が正当な理由なく団体交渉を拒否することは何に当たるか。",
    choices: ["不法行為", "不当労働行為", "債務不履行", "権利濫用"],
    answer: 1,
    explanation: "労働組合法第7条第2号により、正当な理由なく団体交渉を拒否することは不当労働行為に該当します。",
    source: "hardcoded",
  },
  {
    id: "sh-140", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働関係調整法上、労働争議の調整方法として規定されているもので正しくないものはどれか。",
    choices: ["あっせん", "調停", "仲裁", "裁判"],
    answer: 3,
    explanation: "労働関係調整法に規定される労働争議の調整方法は、あっせん、調停、仲裁の3つです。裁判は労働関係調整法の調整方法ではありません。",
    source: "hardcoded",
  },
  {
    id: "sh-141", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働契約法上、使用者が有期労働契約を反復更新している場合、労働者が契約更新の申込みをしたときは、使用者が拒絶することに客観的に合理的な理由がなく社会通念上相当と認められない場合は、同一の労働条件で承諾したものとみなされる（雇止め法理）。",
    answer: true,
    explanation: "労働契約法第19条（雇止め法理の法定化）により、一定の場合に雇止めが制限されます。反復更新により実質的に期間の定めのない契約と同視できる場合等が対象です。",
    source: "hardcoded",
  },
  {
    id: "sh-142", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働契約法第18条に規定する無期転換ルールでは、有期労働契約が通算何年を超えて更新された場合、労働者に無期転換申込権が発生するか。",
    choices: ["1年", "3年", "5年", "10年"],
    answer: 2,
    explanation: "有期労働契約が通算5年を超えて更新された場合、労働者は使用者に対し無期労働契約の締結を申し込むことができます（無期転換ルール）。",
    source: "hardcoded",
  },
  {
    id: "sh-143", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "個別労働関係紛争解決促進法に基づき、都道府県労働局に設置されている紛争調整機関は何か。",
    choices: ["労働審判委員会", "紛争調整委員会", "労働委員会", "公益委員会"],
    answer: 1,
    explanation: "個別労働関係紛争解決促進法に基づき、都道府県労働局に紛争調整委員会が設置されており、あっせんを行います。",
    source: "hardcoded",
  },
  {
    id: "sh-144", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "障害者雇用促進法上、民間企業の法定雇用率は2.3%である（2024年4月以降は段階的に引上げ）。",
    answer: true,
    explanation: "民間企業の障害者法定雇用率は2.3%です（2024年4月から2.5%、2026年7月から2.7%に段階的引上げ予定）。常時43.5人以上の企業に適用されます。",
    source: "hardcoded",
  },
  {
    id: "sh-145", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "高年齢者雇用安定法上、事業主が講じなければならない65歳までの雇用確保措置として正しくないものはどれか。",
    choices: ["定年の引上げ", "継続雇用制度の導入", "定年の定めの廃止", "早期退職優遇制度の導入"],
    answer: 3,
    explanation: "65歳までの雇用確保措置は、(1)定年の引上げ、(2)継続雇用制度の導入、(3)定年の定めの廃止のいずれかです。早期退職優遇制度は雇用確保措置ではありません。",
    source: "hardcoded",
  },
  {
    id: "sh-146", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "次世代育成支援対策推進法上、一般事業主行動計画の策定・届出義務があるのは常時何人以上の企業か。",
    choices: ["51人以上", "101人以上", "301人以上", "501人以上"],
    answer: 1,
    explanation: "常時101人以上の労働者を雇用する事業主は、一般事業主行動計画の策定・届出が義務です。100人以下は努力義務です。",
    source: "hardcoded",
  },
  {
    id: "sh-147", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "女性活躍推進法上、常時301人以上の労働者を雇用する事業主は、女性の活躍に関する情報を公表しなければならない。",
    answer: true,
    explanation: "女性活躍推進法により、常時301人以上（2022年4月からは101人以上）の事業主は、一般事業主行動計画の策定・届出と情報公表が義務付けられています。",
    source: "hardcoded",
  },
  {
    id: "sh-148", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働施策総合推進法（パワハラ防止法）上、職場におけるパワーハラスメントの要素として正しくないものはどれか。",
    choices: ["優越的な関係を背景とした言動", "業務上必要かつ相当な範囲を超えた言動", "労働者の就業環境が害されること", "労働者の同意があること"],
    answer: 3,
    explanation: "パワハラの3要素は(1)優越的な関係を背景、(2)業務上必要かつ相当な範囲を超えた言動、(3)就業環境が害されることです。労働者の同意の有無は要素ではありません。",
    source: "hardcoded",
  },
  {
    id: "sh-149", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "介護休業は、対象家族1人につき通算何日を限度に取得できるか。",
    choices: ["60日", "90日", "93日", "180日"],
    answer: 2,
    explanation: "介護休業は対象家族1人につき通算93日を限度に、3回まで分割取得が可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-150", type: "truefalse", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "労働審判法に基づく労働審判は、原則として3回以内の期日で審理を終結しなければならない。",
    answer: true,
    explanation: "労働審判法第15条により、労働審判は原則3回以内の期日で審理を終結します。迅速な紛争解決を目的とした制度です。",
    source: "hardcoded",
  },
  {
    id: "sh-151", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "産後パパ育休（出生時育児休業）は、子の出生後何週間以内に取得できるか。",
    choices: ["4週間", "8週間", "12週間", "6ヶ月"],
    answer: 1,
    explanation: "2022年10月施行の出生時育児休業（産後パパ育休）は、子の出生後8週間以内に4週間まで取得でき、2回に分割することも可能です。",
    source: "hardcoded",
  },
  {
    id: "sh-152", type: "choice", grade: 1, category: "general-labor" as SharoshiCategory,
    question: "職業安定法上、労働者の募集を行う際に明示しなければならない労働条件に含まれないものはどれか。",
    choices: ["業務内容", "賃金", "労働時間", "社長の経歴"],
    answer: 3,
    explanation: "職業安定法第5条の3により、労働条件の明示事項は、業務内容、賃金、労働時間、就業場所、契約期間等です。社長の経歴は明示事項ではありません。",
    source: "hardcoded",
  },

  // ==========================================================================
  // 社会保険に関する一般常識 (general-social) — 30問
  // ==========================================================================
  {
    id: "sh-153", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "国民健康保険の保険者はどれか。",
    choices: ["国", "都道府県及び市町村と国民健康保険組合", "全国健康保険協会のみ", "社会保険庁"],
    answer: 1,
    explanation: "国民健康保険の保険者は都道府県・市町村（特別区含む）と国民健康保険組合です。",
    source: "hardcoded",
  },
  {
    id: "sh-154", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "後期高齢者医療制度の対象者は原則何歳以上か。",
    choices: ["60歳以上", "65歳以上", "70歳以上", "75歳以上"],
    answer: 3,
    explanation: "75歳以上の者（65歳以上で一定の障害認定を受けた者を含む）が対象です。窓口負担は原則1割（一定以上所得者2割、現役並み所得者3割）です。",
    source: "hardcoded",
  },
  {
    id: "sh-155", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "介護保険の第1号被保険者は65歳以上、第2号被保険者は40歳以上65歳未満の医療保険加入者である。",
    answer: true,
    explanation: "第2号被保険者は特定疾病が原因の場合にのみ介護サービスを受けられます。",
    source: "hardcoded",
  },
  {
    id: "sh-156", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "児童手当の支給対象年齢は原則何歳までか。",
    choices: ["12歳（小学校修了）", "15歳（中学校修了）", "18歳（高校修了）", "20歳"],
    answer: 1,
    explanation: "中学校修了まで（15歳到達年度末まで）が原則です。2024年10月からは高校生年代まで拡充されています。",
    source: "hardcoded",
  },
  {
    id: "sh-157", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "確定拠出年金（DC）について正しいものはどれか。",
    choices: ["運用リスクは事業主が負う", "運用リスクは加入者自身が負う", "給付額があらかじめ確定している", "国が運用を行う"],
    answer: 1,
    explanation: "確定拠出年金は加入者自身が運用し、運用結果に応じて給付額が変動します。確定給付年金（DB）は給付額が確定しています。",
    source: "hardcoded",
  },
  {
    id: "sh-158", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "社会保険労務士は、社会保険労務士法に基づく国家資格者である。",
    answer: true,
    explanation: "社労士法第2条に規定される業務には、申請書等の作成、提出代行、事務代理、紛争解決手続代理、相談指導等があります。",
    source: "hardcoded",
  },
  {
    id: "sh-159", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "介護保険の要介護認定の区分として、要支援は何段階あるか。",
    choices: ["1段階", "2段階", "3段階", "5段階"],
    answer: 1,
    explanation: "介護保険の認定区分は、要支援1・2の2段階と要介護1〜5の5段階、合計7段階です。",
    source: "hardcoded",
  },
  {
    id: "sh-160", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "介護保険の保険者はどれか。",
    choices: ["国", "都道府県", "市町村及び特別区", "全国健康保険協会"],
    answer: 2,
    explanation: "介護保険の保険者は市町村及び特別区です。国・都道府県はそれぞれの立場で財政支援等を行います。",
    source: "hardcoded",
  },
  {
    id: "sh-161", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "介護保険の第1号被保険者の保険料は、原則として年金から天引き（特別徴収）される。",
    answer: true,
    explanation: "第1号被保険者で年額18万円以上の年金を受給している者は、原則として年金から天引き（特別徴収）されます。それ以外は普通徴収（納付書等）です。",
    source: "hardcoded",
  },
  {
    id: "sh-162", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "介護保険サービスの利用者負担は原則何割か。",
    choices: ["1割", "2割", "3割", "所得に応じて異なる"],
    answer: 0,
    explanation: "介護保険サービスの利用者負担は原則1割です。ただし、一定以上の所得がある第1号被保険者は2割又は3割負担となります。",
    source: "hardcoded",
  },
  {
    id: "sh-163", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "船員保険の保険者はどれか。",
    choices: ["国", "全国健康保険協会", "船員保険組合", "日本年金機構"],
    answer: 1,
    explanation: "船員保険の保険者は全国健康保険協会（協会けんぽ）です。2010年1月に社会保険庁の廃止に伴い、協会けんぽに移管されました。",
    source: "hardcoded",
  },
  {
    id: "sh-164", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "国民健康保険には傷病手当金の支給は義務付けられていない（任意給付である）。",
    answer: true,
    explanation: "国民健康保険では、傷病手当金と出産手当金は任意給付とされており、保険者の判断により条例等で定めた場合にのみ支給されます。健康保険（被用者保険）では法定給付です。",
    source: "hardcoded",
  },
  {
    id: "sh-165", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "確定給付企業年金（DB）の種類として正しいものはどれか。",
    choices: ["規約型と基金型", "企業型と個人型", "積立型と賦課型", "報酬比例型と定額型"],
    answer: 0,
    explanation: "確定給付企業年金には、規約型（労使合意の年金規約に基づき、企業等が信託銀行等と契約して実施）と基金型（企業年金基金を設立して実施）の2種類があります。",
    source: "hardcoded",
  },
  {
    id: "sh-166", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "個人型確定拠出年金（iDeCo）に加入できる年齢の上限は原則何歳未満か（2022年5月以降）。",
    choices: ["60歳未満", "65歳未満", "70歳未満", "75歳未満"],
    answer: 1,
    explanation: "2022年5月の改正により、iDeCoの加入可能年齢は原則65歳未満に引き上げられました（国民年金被保険者であることが要件）。",
    source: "hardcoded",
  },
  {
    id: "sh-167", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "生活保護法に基づく保護は、生活扶助、教育扶助、住宅扶助、医療扶助、介護扶助、出産扶助、生業扶助、葬祭扶助の8種類である。",
    answer: true,
    explanation: "生活保護法第11条により、保護は8種類（生活・教育・住宅・医療・介護・出産・生業・葬祭）です。",
    source: "hardcoded",
  },
  {
    id: "sh-168", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "社会保険審査官に対する審査請求は、処分があったことを知った日の翌日から起算して何ヶ月以内にしなければならないか。",
    choices: ["1ヶ月", "2ヶ月", "3ヶ月", "6ヶ月"],
    answer: 2,
    explanation: "社会保険に関する処分に不服がある場合、処分があったことを知った日の翌日から3ヶ月以内に社会保険審査官に審査請求ができます。",
    source: "hardcoded",
  },
  {
    id: "sh-169", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "社会保険審査官の決定に不服がある場合、さらに何に対して再審査請求ができるか。",
    choices: ["厚生労働大臣", "社会保険審査会", "地方裁判所", "都道府県知事"],
    answer: 1,
    explanation: "社会保険審査官の決定に不服がある場合は、社会保険審査会に対して再審査請求をすることができます。",
    source: "hardcoded",
  },
  {
    id: "sh-170", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "高齢者の医療の確保に関する法律（高齢者医療確保法）に基づく特定健康診査（メタボ健診）は、40歳以上75歳未満の医療保険加入者を対象としている。",
    answer: true,
    explanation: "特定健康診査は40歳以上75歳未満の被保険者・被扶養者を対象とし、メタボリックシンドロームに着目した健診です。各医療保険者が実施義務を負います。",
    source: "hardcoded",
  },
  {
    id: "sh-171", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "児童扶養手当は、どのような家庭の児童を対象としているか。",
    choices: ["すべての児童", "ひとり親家庭等の児童", "障害のある児童のみ", "生活保護受給世帯の児童のみ"],
    answer: 1,
    explanation: "児童扶養手当は、父又は母と生計を同じくしていない児童（ひとり親家庭等の児童）を監護する母・父又は養育者に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-172", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "特別児童扶養手当の支給対象となる児童の年齢は何歳未満か。",
    choices: ["15歳未満", "18歳未満", "20歳未満", "22歳未満"],
    answer: 2,
    explanation: "特別児童扶養手当は、精神又は身体に障害を有する20歳未満の児童を監護する父もしくは母又は養育者に支給されます。",
    source: "hardcoded",
  },
  {
    id: "sh-173", type: "truefalse", grade: 1, category: "general-social" as SharoshiCategory,
    question: "日本の社会保障制度は、社会保険、社会福祉、公的扶助、保健医療・公衆衛生の4つの柱で構成されている。",
    answer: true,
    explanation: "日本の社会保障制度は、(1)社会保険（年金・医療・介護・雇用・労災）、(2)社会福祉、(3)公的扶助（生活保護等）、(4)保健医療・公衆衛生の4分野で構成されています。",
    source: "hardcoded",
  },
  {
    id: "sh-174", type: "choice", grade: 1, category: "general-social" as SharoshiCategory,
    question: "国民年金基金は、第何号被保険者が加入できるか。",
    choices: ["第1号被保険者", "第2号被保険者", "第3号被保険者", "すべての被保険者"],
    answer: 0,
    explanation: "国民年金基金は、国民年金の第1号被保険者が任意で加入できる制度です。厚生年金に加入できない自営業者等の年金額を充実させるための制度です。",
    source: "hardcoded",
  },
];

// ---------------------------------------------------------------------------
// ヘルパー関数
// ---------------------------------------------------------------------------

export function getSharoshiQuestions(category?: SharoshiCategory): Question[] {
  if (!category) return sharoshiQuestions;
  return sharoshiQuestions.filter((q) => q.category === category);
}

export function getRandomSharoshiQuestions(count: number): Question[] {
  const shuffled = [...sharoshiQuestions].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, Math.min(count, shuffled.length));
}
